spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/hxg?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
#security:
#  basic:
#    enabled: false
server:
  port: 8080
imooc:
  security:
    browser:
      signInResponseType: REDIRECT
      singInSuccessUrl: /manage.html
      signOutUrl: /demo-logout.html
      signUpUrl: /demo-signUp.html
      signInPage: /demo-signIn.html
# 乱码处理
spring.http.encoding.force: true