spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
#security:
#  basic:
#    enabled: false
server:
  port: 8080
hxg:
  security:
    browser:
      loginPage: /demo-login.html
      loginType: JSON
    validateCode:
      image:
        length: 4
        url: /user/*
# 乱码处理
spring.http.encoding.force: true