spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
security:
  basic:
    enabled: false
server:
  port: 8080

