### client_credentials
POST http://localhost:8090/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic client client

grant_type=client_credentials

### password
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic imooc imoocsecret

grant_type=password&username=user&password=123456

###

###
GET http://localhost:8080/swagger/1
Authorization: bearer 5f89eb6b-82ef-43f1-9ef5-d6cb57f5593d

###
GET http://localhost:8080/client
Authorization: bearer 1b0fc5b5-9c95-4245-801f-36db27d89d80

###
GET http://localhost:8080/basic
Authorization: Basic YmFzaWM6YmFzaWM=  #basic:basic

###
### not-secured
GET http://localhost:8080/not-secured
Authorization: bearer 1b0fc5b5-9c95-4245-801f-36db27d89d80

###