spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/hxg?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
  redis:
    host: db.test.yipicha.com
    database: 14
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url-path: /health
server:
  port: 8080
imooc:
  security:
    oauth2:
      clients[0].clientId: imooc
      clients[0].clientSecret: imoocsecret
      tokenStore: redis
# 乱码处理
spring.http.encoding.force: true
logging:
  level: debug
zuul:
  sensitive-headers:
management:
  security:
    enabled: false
