spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/hxg?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    database: 2
server:
  port: 8080
imooc:
  security:
    oauth2:
      clients[0].clientId: imooc
      clients[0].clientSecret: imoocsecret
      tokenStore: redis
# 乱码处理
spring.http.encoding.force: true
logging:
  level: debug